# Generated by Django 5.0.6 on 2024-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
