# Generated by Django 5.0.6 on 2024-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20240708_1553'),
    ]

    operations = [
    ]
